CFLAGS=-Wall -g

all:
	cc ex0.c -o ex0
	cc ex1.c -o ex1
	cc ex3.c -o ex3
	cc ex4.c -o ex4
	cc ex5.c -o ex5
	cc ex6.c -o ex6
	cc ex7.c -o ex7

clean:
	rm -f ex0
	rm -f ex1
	rm -f ex3
	rm -f ex4
	rm -f ex5
	rm -f ex6
	rm -f ex7
